import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Panawerse Dao Next 13',
  description: 'Generated by Saleh',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
            {/* <Header /> */}
      <body className={inter.className}>{children}</body>
      {/* <Footer/> */}
    </html>
  )
}
